### PR TITLE
The block sprites in the overworld are wrong

### PR DESCRIPTION
**Pull request by IoIxD**
The outline is shown when they're enabled and the filled sprite is shown when they're disabled. You need to add 1 to all the values you set in that part of the code.

This fixes that.

It also moves the block of code to end of the main function, in order to have it be drawn over everything else.

As shown below, I also changed the position of the blocks so that the UI looks a bit cleaner.

### CODE REVIEW

**Review by hexaheximal — CHANGES_REQUESTED** [review]
It looks like you're muxing different states into the same spritesheet by doing one state after another for each frame and then adding an offset.

Please, please, PLEASE, just get rid of this awfulness!

**Comment by IoIxD** [comment]
I'm actually just revising what Kelvin did.

**Comment by hexaheximal** [comment]
> I'm actually just revising what Kelvin did.

That makes sense, and I guess this is an okay fix for now, but this is just such a bad way to design it.

**Comment by IoIxD** [comment]
In general I don't agree with showing all the blocks but I did realize that I can make it better with a for-loop.

**Comment by IoIxD** [comment]
In general I don't like what Kelvin did - I imagined the red block would be a placeholder until a better sprite is drawn - but I did at least make it better with a for loop

**Comment by IoIxD** [comment]
image

Would look much better if I could use color mixing to have the blocks cast a shadow onto each other, but this isn't possible with Brux GDK so this will do.

**Comment by KelvinShadewing** [comment]
Oh, I wanted them in a row to indicate what all blocks have been collected, like the keys you can find.

**Comment by IoIxD** [comment]
Do you want me to change it back? I think that this conveys the same thing.

**Pull request merged**
