### PR TITLE
fixed minor grammar errors

### PR DESCRIPTION
**Pull request by JohnBlood**

### CODE REVIEW

**Comment by Frostwithasideofsalt** [comment]
I was genuinely shocked to find out this pr wasn't fixing some dumb typos i made 

Also don't get rid of install Destructions :(

**Comment by KelvinShadewing** [comment]
"install destructions" is an intential mistake in reference to this video: https://youtu.be/UeHp-DEkJqo

**Comment by JohnBlood** [comment]
It did seem like a strange error to make.

**Comment by KelvinShadewing** [comment]
Also, "speedrunning" is an actual word: https://www.dictionary.com/browse/speedrun

**Comment by JohnBlood** [comment]
My mistake

**Pull request merged**
